apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  annotations:
    'jenkins.io/job-full-name': testfolder/testjob
spec:
  type: service
  lifecycle: experimental
  owner: your-name
